package pt.isec.pa.apoio_poe.model.fsm;

public enum ListingType {
    STUDENTS, PROPOSALS, TEACHERS, APPLICATIONS, STUDENTS_SELFPROPOSALS, PROPOSALS_STUDENTS_WITH_APPLICATION,
    STUDENTS_ASSIGNED, STUDENTS_UNASSIGNED, PROPOSALS_STUDENTS_WITHOUT_APPLICATION, PROPOSALS_FILTERS_STAGE_TWO,
    PROPOSALS_FILTERS_STAGE_THREE, ASSIGNMENTS, STUDENTS_ASSIGNED_WITH_ADVISOR, STUDENTS_ASSIGNED_WITHOUT_ADVISOR, NONE
}
