package pt.isec.pa.apoio_poe.model.fsm;

public enum ListingType {
    STUDENTS, PROPOSALS, TEACHERS, APPLICATIONS, STUDENTS_SELFPROPOSALS, PROPOSALS_STUDENTS_WITH_APPLICATION, PROPOSALS_STUDENTS_WITHOUT_APPLICATION, PROPOSALS_FILTERS, NONE
}
